Import( "subdir_env" )
src = ["src/RoutingGraph.cpp", "src/Route.cpp", "src/RoutingGraphBuilder.cpp", "src/RouteBuilder.cpp", "src/LaneletPath.cpp", "src/RoutingCost.cpp"]

hdr = Glob("include/lanelet2_routing/*.h")
subdir_env.Install( "#/scons_targets/include/lanelet2/lanelet2_routing", [ File( h ) for h in hdr ] )

subdir_env.SharedLibrary( "#/scons_targets/lib/lanelet2/lanelet2_routing", src, LIBS=["lanelet2_core"] )

